repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(node_modules/|venv/|__pycache__/|\.git/)
      - id: end-of-file-fixer
        exclude: ^(node_modules/|venv/|__pycache__/|\.git/)
      - id: check-yaml
        exclude: ^(node_modules/|venv/|__pycache__/|\.git/)
      - id: check-json
        exclude: ^(node_modules/|venv/|__pycache__/|\.git/)
      - id: check-added-large-files
      - id: check-merge-conflict
